# -*- coding: utf-8 -*-
"""analyze_sentimen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnenjGBqjJcPWKpNDwvzlfVzrVocRXbJ
"""

import pandas as pd
import matplotlib.pyplot as plt
from transformers import pipeline

df = pd.read_csv('cafe_reviews.csv')

classifier = pipeline(
    "sentiment-analysis",
    model="blanchefort/rubert-base-cased-sentiment"
)

def analyze_sentiment(text):
    result = classifier(str(text))[0]

    if result['label'] == 'NEUTRAL':
        return 0
    elif result['label'] == 'POSITIVE':
        return 1
    elif result['label'] == 'NEGATIVE':
        return 2

df['predicted_sentiment'] = df['text'].apply(analyze_sentiment)

sentiment_counts = df['predicted_sentiment'].value_counts()

plt.bar(sentiment_counts.index, sentiment_counts.values)

plt.xlabel("Тональность")
plt.ylabel("Количество отзывов")
plt.title("Распределение тональности отзывов (Predicted)")

plt.show()

